Task 6: средства оптимизации библиотеки Pandas

In [80]:
import pandas as pd
import numpy as np

In [81]:
from google.colab import drive   
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [82]:
fines = pd.read_csv('/content/drive/MyDrive/School21/day10/fines.csv') 
fines

         CarNumber  Refund   Fines    Make  Model  Year
0     Y163O8161RUS       2  3200.0    Ford  Focus  1989
1      E432XX77RUS       1  6500.0  Toyota  Camry  1995
2      7184TT36RUS       1  2100.0    Ford  Focus  1984
3     X582HE161RUS       2  2000.0    Ford  Focus  2015
4     92918M178RUS       1  5700.0    Ford  Focus  2014
..             ...     ...     ...     ...    ...   ...
925  AY163O8161RUS       2  3200.0    Ford  Focus  1989
926   AE432XX77RUS       1  6500.0  Toyota  Camry  1995
927   A7184TT36RUS       1  2100.0    Ford  Focus  1984
928  AX582HE161RUS       2  2000.0    Ford  Focus  2015
929  A92918M178RUS       1  5700.0    Ford  Focus  2014

[930 rows x 6 columns]

In [83]:
fines.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CarNumber  930 non-null    object
 1   Refund     930 non-null    int64
 2   Fines      930 non-null    float64
 3   Make       930 non-null    object
 4   Model      919 non-null    object
 5   Year       930 non-null    int64
dtypes: float64(1), int64(2), object(3)
memory usage: 196.6 KB

In [84]:
%%timeit
calc = []
for i in range(0, len(fines)):
  calc.append(fines.iloc[i].Fines / fines.iloc[i].Refund * fines.iloc[i].Year)

340 ms ± 8.16 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [85]:
%%timeit
calc = []
for index, row in fines.iterrows():
  calc.append(row.Fines / row.Refund * row.Year)

62.7 ms ± 988 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [86]:
%%timeit
calc = fines.apply(lambda x: (x.Fines / x.Refund * x.Year), axis=1)

25 ms ± 590 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [87]:
%%timeit
calc = fines.Fines / fines.Refund * fines.Year

242 µs ± 30.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [88]:
%%timeit
calc = fines.Fines.values / fines.Refund.values * fines.Year.values

25.2 µs ± 2.08 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [89]:
%%timeit
fines.query('CarNumber == "O136HO197RUS"')

1.43 ms ± 146 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [90]:
%%timeit
fines.set_index('CarNumber').loc['O136HO197RUS']  #установили в качестве индекса в датафрейме CarNumber

721 µs ± 14.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [91]:
fines.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CarNumber  930 non-null    object
 1   Refund     930 non-null    int64
 2   Fines      930 non-null    float64
 3   Make       930 non-null    object
 4   Model      919 non-null    object
 5   Year       930 non-null    int64
dtypes: float64(1), int64(2), object(3)
memory usage: 196.6 KB

In [92]:
optimized=fines.copy() #скопировали с помощью команды copy() исходный датафрейм в другой под названием optimized

In [105]:
optimized = fines.copy()  #выполнили проведение типа и запустили info(memory_usage='deep') 
optimized['Fines'] = optimized['Fines'].astype(np.float32)
optimized['Refund'] = optimized['Refund'].astype(np.int8)
optimized['Year'] = optimized['Year'].astype(np.int16)
optimized.info( memory_usage = 'deep' )

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CarNumber  930 non-null    object
 1   Refund     930 non-null    int8
 2   Fines      930 non-null    float32
 3   Make       930 non-null    object
 4   Model      919 non-null    object
 5   Year       930 non-null    int16
dtypes: float32(1), int16(1), int8(1), object(3)
memory usage: 181.1 KB

In [102]:
from pandas.api.types import CategoricalDtype

In [108]:
optimized["Model"] = optimized["Model"].astype("category")
optimized["Make"] = optimized["Make"].astype("category")
optimized["CarNumber"] = optimized["CarNumber"].astype("category")

In [109]:
optimized.info( memory_usage = 'deep' )

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CarNumber  930 non-null    category
 1   Refund     930 non-null    int8
 2   Fines      930 non-null    float32
 3   Make       930 non-null    category
 4   Model      919 non-null    category
 5   Year       930 non-null    int16
dtypes: category(3), float32(1), int16(1), int8(1)
memory usage: 63.9 KB

In [40]:
import gc

In [41]:
who_ls

['drive', 'fines', 'gc', 'np', 'optimized', 'pd']

In [42]:
%reset_selective fines

Once deleted, variables cannot be recovered. Proceed (y/[n])?  y

In [43]:
who_ls

['drive', 'gc', 'np', 'optimized', 'pd']

In [44]:
fines

NameError: ignored