Task 1: загрузка и сохранение
В этом упражнении вам нужно загрузить файл журнала и поместить его в подкаталог data в корневом каталоге, который вы используете в рамках этого упражнения. Затем загрузить его в датафрейм, изменить разделитель и сохранить получившийся результат в другой файл.

Ваши задачи в рамках этого упражнения в деталях.

Используя метод read_csv:

отфильтруйте строки с индексами 2 и 3 с помощью аргумента skiprows (мы заведомо знаем, что эти наблюдения были фиктивными);
отфильтруйте последние 2 строки таблицы с помощью аргумента skipfooter (мы знаем, что эти наблюдения тоже были фиктивными);
присвойте столбцам следующие имена: datetime, user;
используйте datetime в качестве столбца индекса.
Переименуйте datetime в date_time.

Используя метод to_csv:

используйте ; в качестве разделителя;
сохраните данные в файл с именем feed-views-semicolon.log.

In [2]:
import pandas as pd
import numpy as np

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
df = pd.read_csv(
    '/content/drive/MyDrive/School21/day10/feed-views.log',
    sep='\t',
    engine='python', 
    header=None, 
    skiprows=[2, 3], 
    skipfooter=2,  
    names = ['datetime', 'user'], 
    index_col = 'datetime'
    )
df

                                 user
datetime
2020-04-17 12:01:08.463179      artem
2020-04-17 12:01:23.743946      artem
2020-04-17 12:35:52.735016      artem
2020-04-17 12:36:21.401412     oksana
2020-04-17 12:36:22.023355     oksana
...                               ...
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel

[1072 rows x 1 columns]

In [5]:
df.index.names

FrozenList(['datetime'])

In [6]:
df.index.names = ['date_time'];df

                                 user
date_time
2020-04-17 12:01:08.463179      artem
2020-04-17 12:01:23.743946      artem
2020-04-17 12:35:52.735016      artem
2020-04-17 12:36:21.401412     oksana
2020-04-17 12:36:22.023355     oksana
...                               ...
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel

[1072 rows x 1 columns]

In [7]:
df.to_csv('/content/drive/MyDrive/School21/day10/feed-views-semicolon.log', sep=';')

ПРОВЕРКА

In [9]:
df.count()

user    1072
dtype: int64

In [10]:
proverka = pd.read_csv('/content/drive/MyDrive/School21/day10/feed-views-semicolon.log', sep=';')
proverka

                       date_time       user
0     2020-04-17 12:01:08.463179      artem
1     2020-04-17 12:01:23.743946      artem
2     2020-04-17 12:35:52.735016      artem
3     2020-04-17 12:36:21.401412     oksana
4     2020-04-17 12:36:22.023355     oksana
...                          ...        ...
1067  2020-05-21 16:36:40.915488  ekaterina
1068  2020-05-21 17:49:36.429237      maxim
1069  2020-05-21 18:45:20.441142  valentina
1070  2020-05-21 23:03:06.457819      maxim
1071  2020-05-21 23:23:49.995349      pavel

[1072 rows x 2 columns]

In [11]:
proverka.head() #сверяем с заданием

                    date_time    user
0  2020-04-17 12:01:08.463179   artem
1  2020-04-17 12:01:23.743946   artem
2  2020-04-17 12:35:52.735016   artem
3  2020-04-17 12:36:21.401412  oksana
4  2020-04-17 12:36:22.023355  oksana